apiVersion: v1
kind: Service
metadata:
  name: ceph-prometheus
  namespace: ceph
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: ceph-prometheus
