apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: ceph
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
  namespace: ceph
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  namespace: ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: ceph
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: ceph-prometheus
  namespace: ceph
  labels:
    prometheus: ceph-prometheus
spec:
  serviceAccountName: prometheus
  resources:
    requests:
      memory: 400Mi
