[
    {
        "targets": [ "10.42.0.1:9283" ],
        "labels": {
            "instance": "ceph_cluster"
        }
    },
    {
        "targets": [ "10.42.0.2:9283" ],
        "labels": {
            "instance": "ceph_cluster"
        }
    },
    {
        "targets": [ "10.42.0.3:9283" ],
        "labels": {
            "instance": "ceph_cluster"
        }
    },
    {
        "targets": [ "10.42.0.4:9283" ],
        "labels": {
            "instance": "ceph_cluster"
        }
    }
]
